#!/bin/sh

# # The first attempt
# set -u
#
# secret="${1}"
# name="${secret##*/}"
# name="${name%%.*}"
# extracted="/tmp/${name}"
#
# [ -z "${WITH_SECRETS_UNSHARED-}" ] && export WITH_SECRETS_UNSHARED=1 && exec unshare -m "${0}" "${@}"
#
# mount -t tmpfs tmpfs /tmp
#
# mkdir "${extracted}"
# gpg --quiet --decrypt "${secret}" | tar -xf - -C "${extracted}"
#
# shift
#
# "${@}"

set -u

# sudo with-secrets sus/adamantia/provision-crypted sops post/persist/cred/etc/sops/default.yaml
# sudo with-secrets sus/adamantia/provision-crypted nix build --verbose --out-link /tmp/adamantia-disko-images .#nixosConfigurations.adamantia.config.system.build.diskoImagesScript && sudo sh -c "/tmp/adamantia-disko-images --build-memory $(cl 1024*12) $(sudo ./scripts/disko-format-files .)" 

path="${1}"

trap 'cryfs-unmount "${path}"' EXIT HUP INT QUIT TERM 

cryfs "${path}-crypted" "${path}"

shift

"${@}"

