#!/bin/bash

shopt -s nullglob
for g in $(find /sys/kernel/iommu_groups/* -maxdepth 0 -type d | sort -V); do
  for d in $g/devices/*; do
    printf '%s\t' "${g##*/}"
    printf '%s\n' "$(lspci -nns ${d##*/} | sed 's/ /    /' | sed 's/Advanced Micro Devices, Inc. //g')"
  done;
  #printf '\n'
done;
