#!/bin/sh

set -u

info() {
  printf >&2 'switch-lang: %s\n' "${1}"
}

switch_hyprland() {
  hyprctl \
    --batch "$(
      hyprctl devices -j |
        jq -r '.keyboards[] | .name' |
        while IFS= read -r keyboard; do
          printf '%s %s %s;' 'switchxkblayout' "${keyboard}" 'next'
        done
    )"
}

switch_x11() {
  xkblayout-state set +1
  command 2>/dev/null -v ev &&
    ev emit 'switch-lang' 'lang' 'change'
}

# Match for Hyprland
[ -z "${switch-}" ] &&
  [ "${XDG_SESSION_TYPE-}" = 'wayland' ] &&
  printf '%s' "${XDG_CURRENT_DESKTOP-}" | grep -qi 'hyprland' &&
  switch='switch_hyprland'

# Match for X11
[ -z "${switch-}" ] &&
  printf '%s' "${XDG_SESSION_TYPE-}" | grep -qi 'x11' &&
  switch='switch_x11'

# Fallback
if [ -z "${switch-}" ]; then
  info 'setting input language for your display server is not supported or XDG_SESSION_TYPE is unset'
  info "display server is: '${XDG_CURRENT_DESKTOP-}' on '${XDG_SESSION_TYPE:-"tty"}'"
  exit 1
fi

# Actual thing
"${switch}"
