#!/bin/sh

sed -E '
  s/RECSIZE/REC/;
  s/MOUNTPOINT/MOUNT/;
  s/PRIMARYCACHE/ARC/;
  s/REFER/REF/;
  s/RATIO/RAT/;
  s/([0-9]\.[0-9]{2})x/\1/;
  s/COMPRESS/COMPR/;
  s/ legacy / unix /
' |
#awk '{ print $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12 }' |
column -t
