#!/bin/sh

clamp() {
	min="${1}"
	max="${2}"
	val="${3}"
  [ $(calc "${val} > ${max}") = 1 ] && val="${max}"
  [ $(calc "${val} < ${min}") = 1 ] && val="${min}"
  printf '%s' "${val}"
}

MAX_ZOOM='50.0'
MIN_ZOOM='1.0'
ZOOM_STEP='0.2'

file="${XDG_RUNTIME_DIR}/zoom-level"
! [ -f "${file}" ] && printf "${MIN_ZOOM}" > "${file}"
zoom_level="$(< "${file}")"


case "${1}" in
  in) new_zoom_level="$(clamp "${MIN_ZOOM}" "${MAX_ZOOM}" "$(calc "${zoom_level} + ${ZOOM_STEP}")")" ;;
  out) new_zoom_level="$(clamp "${MIN_ZOOM}" "${MAX_ZOOM}" "$(calc "${zoom_level} - ${ZOOM_STEP}")")" ;;
  *) new_zoom_level="${1}" ;;
esac

printf '%s' "${new_zoom_level}" > "${file}"
hyprctl keyword 'cursor:zoom_factor' "${new_zoom_level}"
