#!/bin/sh

set -u

: "${SUDO_UID:=$(id -u)}"
: "${SUDO_GID:=$(id -g)}"

path="${1}"
initial_pwd="$(pwd)"
shift

info() {
  printf >&2 'with-secrets: %s\n' "${1}"
}

[ -f "${path}/cryfs.config" ] || { info 'ERROR: directory is not a cryfs repository' && exit 1; }

mount="$(mktemp -d)"
clean=false
cleanup() {
  [ "${clean}" = true ] && return
  clean=true
  cd "${initial_pwd}"
  # NOTE: can fail pretty much only if something else cd'ed into the folder!
  #       spooky!
  for _ in $(seq 3); do
    cryfs-unmount --immediate "${mount}" >/dev/null && break
    sleep 3;
  done
  chown --quiet -R "${SUDO_UID}:${SUDO_GID}" "${path}" >&2
  rmdir "${mount}"
}
trap "cleanup" EXIT HUP INT QUIT TERM

cryfs "${path}" "${mount}" >/dev/null || { info 'ERROR: could not mount' && exit 1; }
cd "${mount}" || { info 'ERROR: could not cd into the temp dir. wut?' && exit 1; }

"${@}"
