#!/bin/sh

# # The first attempt
# set -u
#
# secret="${1}"
# name="${secret##*/}"
# name="${name%%.*}"
# extracted="/tmp/${name}"
#
# [ -z "${WITH_SECRETS_UNSHARED-}" ] && export WITH_SECRETS_UNSHARED=1 && exec unshare -m "${0}" "${@}"
#
# mount -t tmpfs tmpfs /tmp
#
# mkdir "${extracted}"
# gpg --quiet --decrypt "${secret}" | tar -xf - -C "${extracted}"
#
# shift
#
# "${@}"

set -u

: "${SUDO_UID:=$(id -u)}"
: "${SUDO_GID:=$(id -g)}"

path="${1}"
shift
printf '"%s"\n' "${@}"

trap "cryfs-unmount --immediate '${path}' >/dev/null && chown -R ${SUDO_UID}:${SUDO_GID} '${path}-crypted'" EXIT HUP INT QUIT TERM

cryfs "${path}-crypted" "${path}" >/dev/null || exit 1

"${@}"

