#!/bin/sh

set -u
set -x

: "${SUDO_UID:=$(id -u)}"
: "${SUDO_GID:=$(id -g)}"

path="${1}"
initial_pwd="$(pwd)"
shift

mount="$(mktemp -d)"
clean=false
cleanup() {
  ! [ "${clean}" = true ] && return
  clean=true
  cd "${initial_pwd}"
  # NOTE: can fail pretty much only if something else cd'ed into the folder!
  #       spooky!
  for _ in $(seq 3) :; do
    cryfs-unmount --immediate "${mount}" && break
    sleep 3;
  done
  chown -R "${SUDO_UID}:${SUDO_GID}" "${path}" >&2
  rmdir "${mount}"
}
trap "cleanup" EXIT HUP INT QUIT TERM

cryfs "${path}" "${mount}" >/dev/null || exit 1
cd "${mount}" || exit 1

"${@}"
