#!/bin/sh

set -u

info() {
  printf >&2 'sb-lang: %s\n' "${1}"
}

lang_hyprland() {
  hyprctl devices -j |
    jq -r '.keyboards[] | .active_keymap' |
    head -n1 |
    cut -c1-2 |
    tr 'a-z' 'A-Z'
}

lang_x11() {
  xkblayout-state print '%n' | cut -c 1-2 | tr a-z A-Z
}

# Match for Hyprland
[ -z "${listen-}" ] &&
  [ "${XDG_SESSION_TYPE-}" = 'wayland' ] &&
  printf '%s' "${XDG_CURRENT_DESKTOP-}" | grep -qi 'hyprland' &&
  lang='lang_hyprland'

# Match for X11
[ -z "${listen-}" ] &&
  printf '%s' "${XDG_SESSION_TYPE-}" | grep -qi 'x11' &&
  listen='lang_x11'

# Fallback
if [ -z "${lang-}" ]; then
  info 'getting input language for your display server is not supported or XDG_SESSION_TYPE is unset'
  info "display server is: '${XDG_CURRENT_DESKTOP-}' on '${XDG_SESSION_TYPE:-"tty"}'"
  printf '??\n'
  exit 1
fi

# Actual thing
"${lang}"
