#!/bin/sh

set -u

# case "${BLOCK_BUTTON}" in
# 	1) notify-send "🧠 Memory hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
# 	2) setsid -f "$TERMINAL" -e htop ;;
# 	3) notify-send "🧠 Memory module" "\- Shows Memory Used/Total.
# - Click to show memory hogs.
# - Middle click to open htop." ;;
# 	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
# esac

format() {
  printf "%5.2fG" "$(</proc/self/fd/0)"
}

case "${1-}" in
  used) 
    raw_used="$(free -b | awk '/^Mem:/ { print $3 }')"
    zfs_factor=0
    mount | grep -q 'type zfs' &&
      zfs_factor="$(awk '/^size/ { print $3 }' /proc/spl/kstat/zfs/arcstats)"
    calc "(${raw_used} - ${zfs_factor} )/1000^3" | format
    ;;
  total) 
    free --bytes | awk '/^Mem:/ { print $2 / 1024^3 }' | format
    ;;
  *) 
    printf >&2 'sb-memory: arg should be either `used` or `total`\n'
    printf 'ERR'
    ;;
esac
